### ISSUE TITLE
IPA / Verkle tree cleanups

### ISSUE THREAD

**Issue by mratsim** [mratsim/constantine#367]
From https://github.com/mratsim/constantine/pull/364#pullrequestreview-1926092368

## Easy
- [x] there is a `newSeq` introduced that needs to be replaced to avoid dependency on Nim runtime, especially if we want to expose IPA through C/Go/Rust
- [x] some proc like absIntChecker are exported but might be local-only
- [x] scalarMul needs an overload for field element and not just big ints
- [x] views need a splitMiddle functions and StridedView can then be replaced

## Medium
- [x] Fixing verkle tests on Windows (out of stack space) #330
- [x] `createIPAProof` initialization is incomplete and need zero-init: https://github.com/mratsim/constantine/pull/389/commits/da069492243ad5763395840897fab6b3e3069802

## Complex

- [x] evalInDomain / evalOutside domain and the Lagrange form of IPA are duplicates of KZG the polynomial functions (used in EIP-4844) need to be deduplicated and parallelized. See #361.
- [ ] Constant-time dlog square root #358 and #359

**Comment by mratsim** [comment]
Closed by #397
